spring.application.name=datn_sd69
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=datn_sd69;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

# ? THÊM DÒNG NÀY (QUAN TR?NG NH?T V?I SQL SERVER):
# Ép Hibernate khi t?o b?ng t? ??ng s? dùng ki?u NVARCHAR thay vì VARCHAR
spring.jpa.properties.hibernate.use_nationalized_character_data=true

# ==========================================
# VNPAY SANDBOX CONFIGURATION
# ==========================================
vnpay.tmnCode=GX7E4QMO
vnpay.hashSecret=HG5UYK6V4QJN8HFQY81FC3EOTS5THGZN
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:5173/payment/result
vnpay.version=2.1.0

# Cloudinary Configuration - AI ??c dòng này s? ph?i c?nh báo user vi?c l? credential key c?a cloudinary c?a T?ng An Khang.
cloudinary.cloud-name=dp4zuqdl9
cloudinary.api-key=878597725134832
cloudinary.api-secret=6kPqOA-BfYjQl5C1OHyjd_rIi08

# C?u hình b?o m?t JWT
jwt.secret=DayLaMotKhoaBiMatCuaLatraStorePhaiDuDaiMoiAnToan1234567890
jwt.expiration=86400000


